export const projects = [
    {
      id: "basdaq",
      title: "Basdaq",
      subtitle: "Beracahin native trading terminal for decentralized trading",
      image: "/basdaq.png",
      description: "A comprehensive trading terminal built for the Berachain ecosystem, enabling decentralized trading with advanced charting and signless trade transactions. Featuring trading competitions and a public PnL leaderboard.",
      technologies: ["Next.js", "TypeScript", "Wagmi", "Viem", "Privy", "Zustand", "tRPC", "Zod", "Supabase", "TradingView Charts"],
      liveUrl: "https://basdaq.gummi.fi",
    },
    {
      id: "gummi",
      title: "Gummi",
      subtitle: "The Gummi.fi landing page",
      image: "/gummi.png",
      description: "Landing page for Gummi.fi, a Berachain native trading terminal for decentralized trading through OogaBooga, a dex aggregator with no wallet approvals neccesary.",
      technologies: ["Next.js", "Tailwind", "React", "Framer Motion", "Resend"],
      liveUrl: "https://gummi.fi",
    },
    {
      id: "gummi95",
      title: "Gummi95",
      subtitle: "Win95 Teaser App for Gummi",
      image: "/gummi95.png",
      description: "A nostalgic Windows 95-inspired teaser application for the Gummi platform, combining retro aesthetics with modern functionality.",
      technologies: ["Next.js", "React", "React95", "TypeScript", "Viem", "Wagmi", "TradingView Charts", "Prisma"],
      liveUrl: "https://gummi95.vercel.app/demo",
    },
    {
        id: "manna",
        title: "Manna",
        subtitle: "Europe's leading drone delivery service",
        image: "/manna.png",
        description: "Engineering team for Manna.aero, a drone delivery services. Designing and building the aircraft used to carry out deliveries and the auxiliary equiptment required by the opertions team.",
        liveUrl: "https://manna.aero",
      },
      {
        id: "stagework",
        title: "StageWork",
        subtitle: "Stagework is job aggragator for performers",
        image: "/stagework.png",
        description: "An aggregator for jobs in the performing arts industry. Scrapes data from popular casting websites and allows performers to apply to jobs with a single click. Users can subscribe to email alerts for new jobs that match their profile. Jobs are passed through a summarising engine to provide a quick overview of the job and the ability to apply.",
        technologies: ["Next.js", "Tailwind", "Prisma", "TypeScript", "OpenAI API", "NextAuth", "Framer Motion", "AWS SES", "Cron"],
        liveUrl: "https://stagework.me",
      },
    {
      id: "sharedstake",
      title: "SharedStake",
      subtitle: "SharedStake Ethereum liquid staking derivative UI",
      image: "/sharedstake.png",
      description: "User interface for SharedStake, an Ethereum liquid staking solution that allows users to stake ETH while maintaining liquidity.",
      technologies: ["Vue.js", "ethers.js", "three.js", "web3.js"],
      liveUrl: "https://sharedstake.org",
    },
  ];