export const projects = [
    {
      id: "basdaq",
      title: "Basdaq",
      subtitle: "Beracahin native trading terminal for decentralized trading",
      image: "/basdaq.png",
      description: "A comprehensive trading terminal built for the Berachain ecosystem, enabling decentralized trading with advanced charting and order functionality.",
      technologies: ["Next.js", "TypeScript", "Wagmi", "Viem", "Zustand", "tRPC", "Zod", "TradingView Charts"],
      liveUrl: "https://basdaq.gummi.fi",
    },
    {
      id: "gummi",
      title: "Gummi",
      subtitle: "The Gummi.fi landing page",
      image: "/gummi.png",
      description: "Landing page for Gummi.fi, a DeFi platform focused on simplifying crypto asset management with a sleek, intuitive interface.",
      technologies: ["Next.js", "Tailwind", "React", "Framer Motion", "Resend"],
      liveUrl: "https://gummi.fi",
    },
    {
      id: "gummi95",
      title: "Gummi95",
      subtitle: "Win95 Teaser App for Gummi",
      image: "/gummi95.png",
      description: "A nostalgic Windows 95-inspired teaser application for the Gummi platform, combining retro aesthetics with modern functionality.",
      technologies: ["Next.js", "React", "React95", "TypeScript", "Viem", "Wagmi", "TradingView Charts", "Prisma"],
      liveUrl: "https://gummi95.vercel.app/demo",
    },
    {
        id: "manna",
        title: "Manna",
        subtitle: "Europe's leading drone delivery service",
        image: "/manna.png",
        description: "A landing page for Manna.aero, a platform for decentralized trading and trading on Berachain.",
        liveUrl: "https://manna.aero",
      },
      {
        id: "stagework",
        title: "StageWork",
        subtitle: "Stagework is job aggragator for performers",
        image: "/stagework.png",
        description: "A landing page for Stagework, a platform for creating and managing stage plays.",
        technologies: ["Next.js", "Tailwind", "Prisma", "TypeScript", "OpenAI API", "NextAuth", "Framer Motion", "AWS SES", "Cron"],
        liveUrl: "https://stagework.me",
      },
    {
      id: "sharedstake",
      title: "SharedStake",
      subtitle: "SharedStake Ethereum liquid staking derivative UI",
      image: "/sharedstake.png",
      description: "User interface for SharedStake, an Ethereum liquid staking solution that allows users to stake ETH while maintaining liquidity.",
      technologies: ["Vue.js", "ethers.js", "three.js", "web3.js"],
      liveUrl: "https://sharedstake.org",
    },
  ];